### ISSUE TITLE
[Issue #1] top.html origin css

### ISSUE THREAD

**Issue by hufsicehwang** [openInfra-project/AutoWatch-Manage-Server#3]
```css
    <style>
        *,*:before: *:after{
            box-sizing: inherit;
        }

        body,h1,h2,h3{
            margin: 0;
            padding: 0;
            font-weight: normal;
        }

        body {
            background-color: #3c5b9a;
            padding: 0.5rem;
            font-family: tahoma;
        }
        .main{
            width:100%;
            background-color: #e9eaef;
            box-shadow: 20px 20px 20px 20px #143477;
        }
        .top{
            background-color:#3c5b9a;
           
        }
        /* .header{
            display: flex;   #이거 하니까 상단 깨짐,,
        } */
        #topMenu ul li{
            list-style: none;
            float: left;
            line-height: 60px;
            padding: 0 0 0 -30px;

        }
        #topMenu .nav-item{
            color: white;
            width: 60px;
            text-align:left;
            font-size: 14px;
            font-weight: bold;

        }

        #topMenu a{
            text-decoration:none;
        }
        #topIcon ul li{
            list-style: none;
            float: right;
            line-height: 60px;
            padding-right : 20px;
            vertical-align: middle;
            text-align:center;
        }
        #topIcon .nav-item{
            color: white;
            width: 50px;
            font-size: 14px;
            font-weight: bold;
        }
        h2{
            color: white;
            text-align: center;
            font-size: 2rem;
            padding: 0px 0 10px ;
        }
        h3{
            color: white;
            text-align: center;
            font-size: 1rem;
            padding-bottom: 200px;
        }
        .login{
            display: flex;
            width: 400px;
            
            margin: 0 auto;
            background-color : white;
            padding: 10px 30px;
            
        }

        .sidenav {
          height: 40%;
          width: 0;
          right: 0;
          position: fixed;
          z-index: 1;
          top: 14px;
          background-color: #CED8F6;
          background-color: rgba( 255, 255, 255, 0.9 );
          
          transition: 0.5s;
          padding-top: 60px;
        }

        .sidenav a {
          padding: 8px 8px 8px 32px;
          text-decoration: none;
          font-size: 20px;
          color: #818181;
          display: block;
          transition: 0.3s;
        }

        .sidenav a:hover {
          color: #3c5b9a;
        }

        .sidenav .closebtn {
          position: absolute;
          top: 0;
          right: 25px;
          font-size: 36px;
          margin-left: 50px;
        }

        @media screen and (max-height: 450px) {
          .sidenav {padding-top: 30px;}
          .sidenav a {font-size: 15px;}
        }
        .logo{
            width:50%;
            text-align: center;
            margin-bottom : -30px;
        }
    </style>
```
